drop table if exists champion_domain CASCADE;
drop table if exists region_domain CASCADE;
create table champion_domain (id bigint generated by default as identity, name varchar(255) not null, role varchar(255) not null, region_id bigint, primary key (id));
create table region_domain (id bigint generated by default as identity, description varchar(255) not null, name varchar(255) not null, primary key (id));
alter table champion_domain add constraint FKlk22mc7qha4s4hplb1kjs2p00 foreign key (region_id) references region_domain on delete cascade;